### ISSUE TITLE
Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by Silverteal** [clarkwinkelmann/flarum-ext-group-invitation#6] opened 2021-08-15 12:23 UTC
Error while enabling this extension.
DEBUG window shows the message:"
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes in ***\flarum\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:112"

**Comment by clarkwinkelmann** [comment] 2021-08-15 15:25
Are you sure it's caused by this extension? Is there a longer error message?

I've seen this error happen with composite keys in the past, but this extension doesn't have any composite key.

If it really is this extension, it's probably the UNIQUE index on `code` column that causes the issue. But I'm surprised because it should work with the default max key length.

As a workaround you can temporarily edit `vendor/clarkwinkelmann/flarum-ext-group-invitation/migrations/2020_08_02_create_invitations_table.php` and replace `string('code')` with `string('code', 100)`

The size of the index can be as small as 16 if you don't manually enter custom invitation codes in the database.

**Comment by clarkwinkelmann** [comment] 2022-04-01 16:18
I'm going to close this issue as I don't see any improvement I can make to the extension itself, the current default column length should be fine on most systems.

**Closed as completed by clarkwinkelmann** 2022-04-01 16:18 UTC
